### ISSUE TITLE
Agregar Apartado de Tecnologias.

### ISSUE THREAD

**Issue by Dieg001** [FlaviaBrandan/portfolio-template#1]
Hola, me dirijo a usted con el objetivo de darle a conocer que a su portfolio le podría faltar un apartado de las tecnologías con las que esta familiarizada y es capaz de emplear de manera eficiente.
 Sin otro particular saludo a usted atentamente.

**Comment by FlaviaBrandan** [comment]
Hola. Muy buen consejo lo de agregar un nuevo apartado.
